SELECT index_name, table_name, status
FROM user_indexes
WHERE table_name = 'ORDER_REVIEWS';

CREATE INDEX IDX_ORDERS_CUSTOMER ON ORDERS(CUSTOMER_ID); 

CREATE INDEX IDX_ORDERS_ID_STATUS_DATE ON ORDERS(ORDER_ID, ORDER_STATUS, ORDER_PURCHASE_TIMESTAMP);

CREATE INDEX IDX_ORDER_PAYMENTS_TYPE ON ORDER_PAYMENTS(PAYMENT_TYPE);

CREATE INDEX IDX_ORDER_REVIEWS_ORDER

ALTER SESSION SET STATISTICS_LEVEL = ALL;

CREATE TABLE orders_tuned AS
SELECT *
FROM orders
WHERE 1=0;

SELECT index_name, table_name, uniqueness, status
FROM user_indexes
WHERE table_name = 'ORDERS_TUNED';

ALTER INDEX ORDER_TUNED_PK UNUSABLE;

ALTER SESSION ENABLE PARALLEL DML;

ALTER TABLE orders_tuned NOLOGGING;

SET AUTOTRACE ON
INSERT /*+ APPEND PARALLEL(orders_tuned,4) */ INTO orders_tuned
SELECT *
FROM order_temp
WHERE order_purchase_timestamp < TO_DATE('2025-01-01','YYYY-MM-DD');

COMMIT;

ALTER INDEX ORDER_TUNED_PK REBUILD NOLOGGING;

ALTER TABLE orders_tuned LOGGING;

ALTER SESSION DISABLE PARALLEL DML;
SELECT * from v$VERSION;

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY_CURSOR(NULL,NULL,'ALL'));
